/*
 Highcharts JS v6.0.3 (2017-11-14)
 X-range series

 (c) 2010-2017 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(g){"object"===typeof module&&module.exports?module.exports=g:g(Highcharts)})(function(g){(function(d){var g=d.defined,u=d.Color,r=d.seriesTypes.column,k=d.each,v=d.isNumber,q=d.isObject,p=d.merge,n=d.pick,w=d.seriesType,x=d.wrap,y=d.Axis,t=d.Point,z=d.Series;w("xrange","column",{colorByPoint:!0,dataLabels:{verticalAlign:"middle",inside:!0,formatter:function(){var a=this.point.partialFill;q(a)&&(a=a.amount);g(a)||(a=0);return 100*a+"%"}},tooltip:{headerFormat:'\x3cspan style\x3d"font-size: 0.85em"\x3e{point.x} - {point.x2}\x3c/span\x3e\x3cbr/\x3e',
pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.yCategory}\x3c/b\x3e\x3cbr/\x3e'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:d.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,getColumnMetrics:function(){function a(){k(c.series,function(a){var b=a.xAxis;a.xAxis=a.yAxis;a.yAxis=b})}var b,c=this.chart;a();b=r.prototype.getColumnMetrics.call(this);a();return b},cropData:function(a,
b,c,f){b=z.prototype.cropData.call(this,this.x2Data,b,c,f);b.xData=a.slice(b.start,b.end);return b},translatePoint:function(a){var b=this.xAxis,c=this.columnMetrics,f=this.options.minPointLength||0,e=a.plotX,d=n(a.x2,a.x+(a.len||0)),h=b.translate(d,0,0,0,1),d=h-e,m=this.chart.inverted,l=n(this.options.borderWidth,1)%2/2;f&&(f-=d,0>f&&(f=0),e-=f/2,h+=f/2);e=Math.max(e,-10);h=Math.min(Math.max(h,-10),b.len+10);a.shapeArgs={x:Math.floor(Math.min(e,h))+l,y:Math.floor(a.plotY+c.offset)+l,width:Math.round(Math.abs(h-
e)),height:Math.round(c.width),r:this.options.borderRadius};e=a.shapeArgs.x;f=e+a.shapeArgs.width;0>e||f>b.len?(e=Math.min(b.len,Math.max(0,e)),f=Math.max(0,Math.min(f,b.len)),b=f-e,a.dlBox=p(a.shapeArgs,{x:e,width:f-e,centerX:b?b/2:null})):a.dlBox=null;a.tooltipPos[0]+=m?0:d/2;a.tooltipPos[1]-=m?d/2:c.width/2;if(b=a.partialFill)q(b)&&(b=b.amount),v(b)||(b=0),c=a.shapeArgs,a.partShapeArgs={x:c.x,y:c.y,width:c.width,height:c.height,r:this.options.borderRadius},a.clipRectArgs={x:c.x,y:c.y,width:Math.round(c.width*
b),height:c.height}},translate:function(){r.prototype.translate.apply(this,arguments);k(this.points,function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var c=this.options,f=this.chart.renderer,e=a.graphic,d=a.shapeType,h=a.shapeArgs,m=a.partShapeArgs,l=a.clipRectArgs,g=a.partialFill,k=a.selected&&"select",n=c.stacking&&!c.borderRadius;if(a.isNull)e&&(a.graphic=e.destroy());else{if(e)a.graphicOriginal[b](p(h));else a.graphic=e=f.g("point").addClass(a.getClassName()).add(a.group||this.group),
a.graphicOriginal=f[d](h).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);m&&(a.graphicOverlay?(a.graphicOverlay[b](p(m)),a.clipRect.animate(p(l))):(a.clipRect=f.clipRect(l.x,l.y,l.width,l.height),a.graphicOverlay=f[d](m).addClass("highcharts-partfill-overlay").add(e).clip(a.clipRect)));a.graphicOriginal.attr(this.pointAttribs(a,k)).shadow(c.shadow,null,n);m&&(q(g)||(g={}),q(c.partialFill)&&(g=p(g,c.partialFill)),b=g.fill||u(a.color||this.color).brighten(-.3).get(),a.graphicOverlay.attr(this.pointAttribs(a,
k)).attr({fill:b}).shadow(c.shadow,null,n))}},drawPoints:function(){var a=this,b=this.chart.pointCount<(a.options.animationLimit||250)?"animate":"attr";k(a.points,function(c){a.drawPoint(c,b)})}},{init:function(){t.prototype.init.apply(this,arguments);var a;a=this.series;var b=a.chart.options.chart.colorCount;this.y||(this.y=0);a.options.colorByPoint&&(a=a.options.colors||a.chart.options.colors,b=a.length,!this.options.color&&a[this.y%b]&&(this.color=a[this.y%b]));this.colorIndex=this.y%b;return this},
getLabelConfig:function(){var a=t.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});x(y.prototype,"getSeriesExtremes",function(a){var b=this.series,c,d;a.call(this);this.isXAxis&&(c=n(this.dataMax,-Number.MAX_VALUE),k(b,function(a){a.x2Data&&k(a.x2Data,function(a){a>c&&(c=a,d=!0)})}),d&&(this.dataMax=c))})})(g)});
