dependencies {
    api project(':xcore')
    implementation 'org.apache.activemq:activemq-broker:5.18.6'
}

group = 'com.xwintop'
version = '0.0.2'
description = 'x-ActiveMqTool'

//打jar包需要包含依赖的配置
jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from { configurations.compileClasspath.findAll { it.name.contains("activemq-broker")
    || it.name.contains("javax.annotation-api")
    || it.name.contains("jackson-databind")
    || it.name.contains("jackson-annotations")
    || it.name.contains("jackson-core")
    || it.name.contains("jackson-bom")
    || it.name.contains("activemq-client")
    || it.name.contains("jakarta.jms-api")
    || it.name.contains("hawtbuf")
    || it.name.contains("activemq-openwire-legacy")
    }.collect { zipTree(it) } }
}